server:
  port: 8858

spring:

  application:
    name: finance-business-configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.42/z-wuye?serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848