spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/z-wuye?serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: http://localhost:8848  #nacos的服务地址
mybatis-plus:
  global-config:
    db-config:
      id-type: auto