spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.42/z-wuye?serverTimezone=UTC
    username: root
    password: 123456
  application:
    name:house-manager
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:${oa.empphoto}
server:
  port: 8082
  servelt:
    context-path: /

debug: false


